### PR TITLE
WIP_tests

### PR DESCRIPTION
**Pull request by tsbutler**
Here are the tests we came up with for approval.

### CODE REVIEW

**Comment by sumeetjain** [comment]
Looks good. You need at least one test for just the dictionary's method too though.

**Comment by sumeetjain** [comment]
Tests are :+1:

**Comment by tsbutler** [comment]
We've got through the first hurdle, i.e., if the string is a word itself, that test passes.  So we're moving on to the simple case where the words don't have anything to trip us up.  So, the first word it finds, it would bite off on and move on to the next.  The code we've got algorithmically seems to work, but when we run it through rake it doesn't pass.  Specifically, it says that it is producing a nil output and we would expect it to produce something, even if it's a jumble of letters.  So, we're not sure why it's kicking out nil and not some sort of output.  That's what we are most concerned with right now.  Thanks.

**Comment by sumeetjain** [comment]
Give this a go:

``` ruby
def segment_string(str)
  i = 0
  index = 0
  cut = 1
  arr = []

  if valid_word?(str) == true
    puts "str is itself a valid word. That was easy."
    arr << str

  elsif
    puts "str is not a word, so doing this the hard way:"

    while i < str.length
      puts "---------------- BEGINNING LOOP -------------------"
      puts "i is #{i}"
      puts "index is #{index}"
      puts "cut is #{cut}"

      test_word = str[index, cut]
      puts "test_word is #{test_word}"

      if valid_word?(test_word)
        puts "#{test_word} is a valid word! Adding it to arr"

        arr << test_word

        puts "Now arr is #{arr}. Incrementing values..."

        index += test_word.length
        puts "index is now #{index}"

        cut = 1
        puts "cut is now #{cut}"

        i += 1
        puts "i is now #{i}"

        puts "Returning arr"
        arr
        # Do you want to be returning arr here? What's it do?
      elsif valid_word?(test_word) == false
        puts "#{test} is not a word :( Moving on..."

        cut += 1
        puts "cut is now #{cut}"

        i += 1
        puts "i is now #{i}"
      end
    end  
  end
end
```

It's your exact code, but I added a bunch of `puts` statements so you can see what is happening as it's happening.

Consider "commenting out" all of your tests except one to get less output in Terminal. Otherwise you'll see this output for all the tests.

**Comment by tsbutler** [comment]
Okay, the latest commit, we're trying to start incorporating the skip_counter into our next iteration of a solution.  We're just trying at this point to see if our skip counter is advancing appropriately to put us back into our while loop and steer the computer onto the right path in that code.  What the code itself is is still being sorted out, but it kicks back an error telling us that in line 36 there's a = in a conditional instead of a == and while that's true, that was us reassigning the value 1 to our skip_counter variable and not asserting equality, so we're a bit confused on that.  We have some ideas for moving forward, but this is a little hitch that's slowing us.  Thanks.

**Comment by halfghaninne** [comment]
What happens if you try assigning 0 or 1 to `skip_counter` by using `+= 1` and `-=1`? Does that change your error?

**Comment by tsbutler** [comment]
Here's our solution.  I commented it out, but am of course open to suggestions.  Group: Thorin Butler, Tyler Fisher, Ryan Newell

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
