### PR TITLE
Working on Tests

### PR DESCRIPTION
**Pull request by mel-d**

### CODE REVIEW

**Comment by mel-d** [comment]
I'm getting this error:
  1) Error:
StringSegmenterTest#test_run_through_segmentation:
NoMethodError: private method `set_segment_test_vars' called for #<Segmentation:0x007fdf130075b8>
Did you mean?  set_segment_plurals_test_vars
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/string_segmenter_test.rb:8:in`test_run_through_segmentation'

when I try to run rake. Everything was working before I started trying to convert the tests to work with OOP-- and I don't understand how this method could be private? Even though it's inside a class, I wrote a method specifically to set the variables for this test. It's the same thing I did with all my RPS tests, so I'm out of ideas as to what I could be doing wrong here.

**Comment by sumeetjain** [comment]
Believe it or not, I think fixing the indentation in lib/string_segmenter.rb will reveal the issue.

**Comment by sumeetjain** [comment]
When I run this, the tests don't pass. Are you getting passing tests?

**Comment by mel-d** [comment]
That's weird. Yes, they are passing for me--here's my message:

# Running:

..reached end of string
finalArray is ["turtle", "blue", "train", "trust"]
.startHereValue value is 5
reached end of string
finalArray is ["asset", "smiles", "birth", "five"]
.

Finished in 0.001548s, 2584.5871 runs/s, 2584.5871 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
➜  ruby-toy__string-segmentation git:(master)

**Comment by sumeetjain** [comment]
Whoops–you're right. Looking more closely now...

**Comment by sumeetjain** [comment]
:+1:

**Comment by mel-d** [comment]
Is there something wrong with the code that made it not pass for you??

**Comment by mel-d** [comment]
Aahhh, just saw your Slack message--nvm

**Comment by sumeetjain** [comment]
Nope. Was just accidentally looking at old code.

**Pull request closed without merging**
