### PR TITLE
String Segmenter Test

### PR DESCRIPTION
**Pull request by mel-d**

### CODE REVIEW

**Comment by mel-d** [comment]
With the dictionary test, "word" is what I'll call the variable that represents the return I'll get from my program. (That might be obvious; I just thought I'd add that bit of info just in case.)

**Comment by sumeetjain** [comment]
Do these tests run? They look to me like they'd cause errors.

**Comment by mel-d** [comment]
I thought they weren't supposed to run without errors until I had finished all the files--I'll c+p you the results I get in iTerm to see if that's what's supposed to be happening.

**Comment by mel-d** [comment]
This is from the dictionary test:
  1) Error:
DictionaryTest#test_dictionary:
NameError: undefined local variable or method `dictionary' for #<DictionaryTest:0x007fc01c8be230>
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/dictionary_test.rb:6:in`test_dictionary'

  2) Error:
StringSegmenterTest#test_string_segmenter:
ArgumentError: wrong number of arguments (given 1, expected 2..3)
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/string_segmenter_test.rb:7:in `test_string_segmenter'

  3) Error:
StringSegmenterTest#test_string_plurals:
ArgumentError: wrong number of arguments (given 1, expected 2..3)
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/string_segmenter_test.rb:12:in `test_string_plurals'

3 runs, 0 assertions, 0 failures, 3 errors, 0 skips

**Comment by mel-d** [comment]
From the string segmenter test:
EEE

Finished in 0.001114s, 2693.3657 runs/s, 0.0000 assertions/s.

  1) Error:
StringSegmenterTest#test_string_plurals:
ArgumentError: wrong number of arguments (given 1, expected 2..3)
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/string_segmenter_test.rb:12:in `test_string_plurals'

  2) Error:
StringSegmenterTest#test_string_segmenter:
ArgumentError: wrong number of arguments (given 1, expected 2..3)
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/string_segmenter_test.rb:7:in `test_string_segmenter'

  3) Error:
DictionaryTest#test_dictionary:
NameError: undefined local variable or method `dictionary' for #<DictionaryTest:0x007fd6ac0c0618>
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/dictionary_test.rb:6:in`test_dictionary'

3 runs, 0 assertions, 0 failures, 3 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:tests" -I"/Users/melindadeinert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib" "/Users/melindadeinert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "tests/*_/__test.rb" ]

**Comment by sumeetjain** [comment]
The tests should _run_ without error, but they won't _pass_ until you've completed the full assignment.

So currently, the errors you're getting indicate that the tests themselves are not written correctly.

Take a look at the tests I wrote for your Prep Work from before, and see if you can get any additional clarity from them as examples. If not, let us know and we can explain.

**Comment by mel-d** [comment]
It seems like the string segmenter test is running fine now. The dictionary test is still returning the same error.

What I'm not understanding is why it's telling me that 'dictionary' is undefined? It seems like the dictionary array should be there beings how it says 'require 'dictionary''. Do I need to do more to bring the dictionary into this test file?

**Comment by mel-d** [comment]
Update to my question: I realized that my dictionary test was basically what I was supposed to be putting into the valid_word method. So now, I have a similar question to the one I just asked up there ^, but with a different variable. 

Here's what I get now:
  3) Error:
DictionaryTest#test_dictionary:
NameError: undefined local variable or method `word' for #<DictionaryTest:0x007fc970a63a10>
    /Users/melindadeinert/Code/ruby-toy__string-segmentation/tests/dictionary_test.rb:6:in`test_dictionary'

And my question is: Why isn't 'word' defined? It's included in the 'dictionary' file, which is required as part of this dictionary test.

**Comment by sumeetjain** [comment]
`word` is scoped to be within the `valid_word?` method. It doesn't exist outside the method's definition.

In your test, you should be using actual sample words to _run_ your method. Notice how in the Prep Work tests I wrote for you, I am using real values.

**Comment by sumeetjain** [comment]
:+1:

**Comment by mel-d** [comment]
I've gotten a little stuck and am wondering if my troubles lie in one particular line of my code--is the line "if valid_word?(collect) == true" a valid way to do things? I haven't found examples of anything like this online, but I'm lost as to how else to incorporate the valid_word method.

**Comment by halfghaninne** [comment]
Edited to be more precise.

That conditional is valid, but as it's written now, `collect` is an array, but your dictionary only includes strings. So even thoughthe `valid_word?` method you wrote will take that an array as an argument, it should return false, because the `dictionary` array does not include the `collect` array

**Comment by mel-d** [comment]
^ This sync is my end-of-day product that solves the simple problems but can't yet handle words with other words inside them.

**Comment by mel-d** [comment]
I'm trying to work through how to incorporate a skip counter. I feel like I've set up a decent (although maybe not totally correct?) set of if statements (when i == collect[-1]; if collect.empty? == false) that'll start the code over when my iterator has gotten to the last letter, and if my array to collect letters still has anything left in it that hasn't been designated a dictionary word. I'm just confused about what exactly a skip counter should look like and where it needs to be set equal to 0. 

Another side question about the line "when i == collect[-1]": will this start the code over when my iterator gets to the last letter, or after it has processed the last letter? If it's the former, is there any better way to say "start over after this string has been finished"?

**Comment by mel-d** [comment]
Kinda relatedly, should I be worried about this message on iTerm when I sync?:

git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

**Comment by mel-d** [comment]
(I just re-synced because I changed a couple of small things, but my three questions from before are the same.)

**Comment by mel-d** [comment]
Struggling with deleting the max value from a hash; here's what I have:

```
    finalWord = wordHash.max_by { |k, v| v }[0]
    wordHash.delete(finalWord)
```

Is there something wrong with this? It seems like I get an error message no matter what variation of this I try.

**Comment by mel-d** [comment]
(Just for the record, I want to delete both the key and value).

**Comment by halfghaninne** [comment]
I would expect `wordHash.max_by { |k, v| v}` to return a {k, v} pair. What are you trying to access by including `[0]`?

**Comment by mel-d** [comment]
Adding [0] returns only the key and [1] returns only the value.

**Comment by mel-d** [comment]
I don't know if this is kosher, but it's worked every time I've tried it thus far.

**Comment by halfghaninne** [comment]
What happens if we remove it?

**Comment by halfghaninne** [comment]
So, instead:

```
  finalWord = wordHash.max_by { |k, v| v }
    wordHash.delete(finalWord.keys)
```

**Comment by mel-d** [comment]
^This latest commit can solve the problem unless there is more than one smaller word within a greater word.

**Comment by mel-d** [comment]
^edited to fulfill the assignment, even though I haven't fixed the above problem.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
