### PR TITLE
String Segmentation WIP

### PR DESCRIPTION
**Pull request by amymariewall**
This is just to create a new pull request to ask for help, nothing really has been added or changed.

### CODE REVIEW

**Comment by halfghaninne** [comment]
In theory, yes. Failures for a test on a method that you haven't written yet are to be expected. I'm taking a look at your code now.

**Comment by halfghaninne** [comment]
Your syntax looks great. Are there other edge cases you want to consider in the StringSegmenterTest?

**Comment by amymariewall** [comment]
I am not sure. It says in the assignment that every character in our string will be part of a word, so I won't have to deal with any circumstances where there are extraneous characters that don't belong to a word. That seems to really limit the inputs that I would have to test for to be strings that contain real words as defined by my dictionary. 

If I oversimplifying that?

**Comment by halfghaninne** [comment]
There may be other edge cases that come up (for example strings like "cathelpingfrog" or "catsfrog"), but you can consider those later if you'd like. You're welcome to start moving forward.

**Comment by amymariewall** [comment]
I just wanted to keep sharing my progress so I could ask questions.

I am not there yet, but there are some concepts I used that I don't fully understand, including why adding .dup worked to solve some problems I was encountering with my variable assignment. I am looking into that (and a bunch of other things) more.

**Comment by amymariewall** [comment]
I am getting closer, but I am still encountering an error when I test with string that include word combinations like "blueshark", where the s is not part of the first word, but necessary for the second word.

**Comment by amymariewall** [comment]
I reworked it using the skip counter strategy.

**Comment by amymariewall** [comment]
The working skip counter version is in the string_segmenter.rb file, and the dictionary is still in the dictionary.rb file. The rest are just versions that can be ignored!

**Pull request closed without merging**
